# Generated by Django 5.0.2 on 2025-03-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code_expires_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
    ]
