# Generated by Django 5.0.2 on 2025-03-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_code_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель'), ('manager', 'Менеджер'), ('administrator', 'Администратор')], default='student', max_length=20),
        ),
    ]
