# Generated by Django 5.0.2 on 2025-03-11 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Посещаемость', 'verbose_name_plural': 'Посещаемость'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='homework_file',
            field=models.FileField(blank=True, null=True, upload_to='homework_files/', verbose_name='Файл с домашним заданием'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='homework_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время сдачи домашнего задания'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Баллы'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='additional_materials',
            field=models.TextField(blank=True, help_text='Ссылки на дополнительные материалы, литературу и т.д.', null=True, verbose_name='Дополнительные материалы'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(default=1, help_text='Основной текст урока', verbose_name='Содержание урока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_deadline',
            field=models.DateTimeField(blank=True, help_text='Крайний срок сдачи домашнего задания', null=True, verbose_name='Срок сдачи ДЗ'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Является ли урок обязательным для прохождения', verbose_name='Обязательный урок'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практическое занятие'), ('seminar', 'Семинар'), ('test', 'Тест')], default='lecture', max_length=20, verbose_name='Тип занятия'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=100, help_text='Максимальный балл за урок', verbose_name='Максимальный балл'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='presentation_url',
            field=models.URLField(blank=True, help_text='Ссылка на презентацию к уроку', null=True, verbose_name='Ссылка на презентацию'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ссылка на видеозапись урока', null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий преподавателя'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(verbose_name='Краткое описание урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True, help_text='Задание для самостоятельной работы', null=True, verbose_name='Домашнее задание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(help_text='Порядковый номер урока в курсе', verbose_name='Порядковый номер'),
        ),
    ]
